// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBM9I4kRIESKKPtEqNBZnRMmpwRagNaY',
    appId: '1:101788079811:web:b4f47a862c9e3d22f53476',
    messagingSenderId: '101788079811',
    projectId: 'github-clone-flutter',
    authDomain: 'github-clone-flutter.firebaseapp.com',
    storageBucket: 'github-clone-flutter.appspot.com',
    measurementId: 'G-JF4JV7XEV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAviwBtq1C0ulefYE_1Z0kI7IDbI8mO_I4',
    appId: '1:101788079811:android:4c9d15829df9e059f53476',
    messagingSenderId: '101788079811',
    projectId: 'github-clone-flutter',
    storageBucket: 'github-clone-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMvV0BMg1uq9F7Bvwvr2oH0GbFEQYwMko',
    appId: '1:101788079811:ios:44fb548823881195f53476',
    messagingSenderId: '101788079811',
    projectId: 'github-clone-flutter',
    storageBucket: 'github-clone-flutter.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );
}
